param(
    [string]$ProjectRoot = (Join-Path $PSScriptRoot '..\NIM_Translator')
)

$ErrorActionPreference = 'Stop'
$revision = 'fb047fb395f45ccf1129f8eaee672c9dfa99152e'
$fontToolsVersion = '4.63.0'
$baseUrl = "https://raw.githubusercontent.com/microsoft/fluentui-system-icons/$revision"
$manifestPath = Join-Path $PSScriptRoot 'FluentIconSubset.json'
$entries = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
$work = Join-Path ([System.IO.Path]::GetTempPath()) ('nim-fluent-icons-' + [Guid]::NewGuid().ToString('N'))
$fontDirectory = Join-Path $ProjectRoot 'Assets\Fonts'
$licenseDirectory = Join-Path $ProjectRoot 'ThirdParty\FluentSystemIcons'
$generatedDirectory = Join-Path $ProjectRoot 'Application\Generated'

New-Item -ItemType Directory -Path $work, $fontDirectory, $licenseDirectory, $generatedDirectory -Force | Out-Null

try {
    $sourceMap = Join-Path $work 'Regular.json'
    $sourceFont = Join-Path $work 'Regular.ttf'
    $license = Join-Path $work 'LICENSE'
    $notice = Join-Path $work 'NOTICE'
    Invoke-WebRequest "$baseUrl/fonts/FluentSystemIcons-Regular.json" -OutFile $sourceMap
    Invoke-WebRequest "$baseUrl/fonts/FluentSystemIcons-Regular.ttf" -OutFile $sourceFont
    Invoke-WebRequest "$baseUrl/LICENSE" -OutFile $license
    Invoke-WebRequest "$baseUrl/NOTICE" -OutFile $notice

    $upstream = @{}
    $sourceObject = Get-Content -LiteralPath $sourceMap -Raw | ConvertFrom-Json
    foreach ($property in $sourceObject.PSObject.Properties) {
        $upstream[$property.Name] = [int]$property.Value
    }
    $codepoints = [System.Collections.Generic.List[string]]::new()
    $registryLines = [System.Collections.Generic.List[string]]::new()
    $semanticNames = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
    $glyphValues = [System.Collections.Generic.HashSet[int]]::new()

    foreach ($entry in $entries) {
        if (-not $semanticNames.Add($entry.semantic)) { throw "Duplicate semantic icon '$($entry.semantic)'." }
        if (-not $upstream.ContainsKey($entry.upstream)) { throw "Unknown upstream icon '$($entry.upstream)'." }
        $codepoint = [int]$upstream[$entry.upstream]
        if (-not $glyphValues.Add($codepoint)) { throw "Duplicate glyph U+$($codepoint.ToString('X'))." }
        $codepoints.Add(('U+{0:X}' -f $codepoint))
        $fallback = ([string]$entry.fallback).Replace('"', '\"')
        $registryLines.Add(
            "            { PreviewIconName.$($entry.semantic), new PreviewIconDefinition($codepoint, `"$($entry.semantic)`", `"$($entry.upstream)`", `"$fallback`") },")
    }

    $fontTools = Join-Path $work 'fonttools'
    python -m pip install --disable-pip-version-check --no-input --quiet --target $fontTools "fonttools==$fontToolsVersion"
    if ($LASTEXITCODE -ne 0) { throw 'The pinned fonttools package could not be installed.' }
    $targetFont = Join-Path $fontDirectory 'NIMFluentIcons.ttf'
    $pythonPath = $env:PYTHONPATH
    try {
        $env:PYTHONPATH = $fontTools
        python -m fontTools.subset $sourceFont "--output-file=$targetFont" "--unicodes=$($codepoints -join ',')" `
            --notdef-glyph --notdef-outline --recommended-glyphs --layout-features='*' --name-IDs='*' `
            --name-legacy --name-languages='*' --no-recalc-timestamp
        if ($LASTEXITCODE -ne 0) { throw 'Font subsetting failed.' }
    }
    finally {
        $env:PYTHONPATH = $pythonPath
    }

    Copy-Item -LiteralPath $license -Destination (Join-Path $licenseDirectory 'LICENSE.txt') -Force
    Copy-Item -LiteralPath $notice -Destination (Join-Path $licenseDirectory 'NOTICE.txt') -Force

    $registryTemplate = @'
// <auto-generated />
using System.Collections.Generic;

namespace NIM.UIManagement.Preview
{
    internal static partial class PreviewIconRegistry
    {
        private static readonly IReadOnlyDictionary<PreviewIconName, PreviewIconDefinition> Definitions =
            new Dictionary<PreviewIconName, PreviewIconDefinition>
        {
__REGISTRY__
        };
    }
}
'@
    $registry = $registryTemplate.Replace('__REGISTRY__', ($registryLines -join [Environment]::NewLine))
    [System.IO.File]::WriteAllText(
        (Join-Path $generatedDirectory 'PreviewIconRegistry.g.cs'),
        $registry.Replace("`r`n", "`n"),
        [System.Text.UTF8Encoding]::new($false))

    $sourceRecord = [ordered]@{
        upstream = 'https://github.com/microsoft/fluentui-system-icons'
        revision = $revision
        variant = 'Regular'
        generator = "fonttools $fontToolsVersion"
        sourceFontSha256 = (Get-FileHash -LiteralPath $sourceFont -Algorithm SHA256).Hash.ToLowerInvariant()
        subsetFontSha256 = (Get-FileHash -LiteralPath $targetFont -Algorithm SHA256).Hash.ToLowerInvariant()
        iconCount = $entries.Count
    } | ConvertTo-Json
    [System.IO.File]::WriteAllText(
        (Join-Path $licenseDirectory 'SOURCE.json'),
        $sourceRecord.Replace("`r`n", "`n") + "`n",
        [System.Text.UTF8Encoding]::new($false))
}
finally {
    if (Test-Path -LiteralPath $work) { Remove-Item -LiteralPath $work -Recurse -Force }
}
